import Head from "next/head";
import { useCallback, useState } from "react";
import styles from "src/styles/Home.module.css";
import { TodoItem } from "src/components/TodoItem/index";

export default function Home() {
  const [todoText, setTodoText] = useState("");
  const [array, setArray] = useState([]);

  const handleChange = useCallback((e) => {
    setTodoText(e.target.value.trim());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleAddTask = useCallback(() => {
    setArray((preArray) => {
      if(todoText === "") {
        alert("必ず何かを入力してください！");
        return preArray;
      }
      const newArray = [...preArray, todoText];
      return newArray;
    });
  }, [todoText]);

  return (
    <div className={styles.container}>
      <Head>
        <title>To-do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>To-do App</h1>
        <div className={styles.grid}>
          <div>
            <input value={todoText} onChange={handleChange} />
            <button className={styles.enterButton} onClick={handleAddTask}>
              Enter
            </button>
          </div>

          <ul className={styles.toDoList}>
            {array.map((item) => {
              return <TodoItem key={item} text={item}/>;
            })}
          </ul>
        </div>
      </main>
    </div>
  );
}
